config/routes.rb
Rails.application.routes.draw do
  resources :pk_results
  resources :prizes
  resources :assaults
  resources :pk_data
  resources :new_defeat_enemies
  resources :new_battle_enemies
  resources :duel_results
  resources :battle_results
  get "bosses",  :to => "new_next_enemies#boss",  :as => "bosses"
  resources :new_next_enemies
  resources :next_duel_infos
  resources :next_battle_infos
  resources :next_battle_enemies
  resources :party_infos
  resources :parties
  get "pk_histories",  :to => "current_areas#pk",  :as => "pk_histories"
  get "current_area/totals",  :to => "current_areas#total",  :as => "current_area_totals"
  resources :current_areas
  resources :area_data
  resources :init_equips
  resources :new_skills
  resources :new_embryos
  resources :new_item_fukas
  resources :new_items
  resources :items
  resources :skills
  resources :skill_data
  resources :embryos
  resources :embryo_names
  resources :productions
  resources :statuses
  resources :proper_names
  resources :names
  resources :uploaded_checks
  get 'top_page/privacy'
  root 'top_page#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/top_page_controller.rb
class TopPageController < ApplicationController
  def index
    @latest_result = Name.maximum("result_no")
    @latest_generate = Name.where(result_no: @latest_result).maximum("generate_no")
    @uploaded_result = UploadedCheck.maximum("result_no")
  end
end

app/helpers/top_page_helper.rb
module TopPageHelper
    def top_text(result_no, generate_no, uploaded)
        if !result_no then return "---" end
        generate_text = ""
        generate_text = "再" if generate_no > 0
        num = 2

        while num <= generate_no do
            num += 1
            generate_text += "再"
        end

        text = "第" + sprintf("%d", result_no) + "回" + generate_text

        if result_no == uploaded then
            text += "更新結果まで反映済です。"
        else
            text += "更新結果のデータに更新中です…"
        end

        text
    end
end

app/views/top_page/index.html.haml
%h1 IkkiFantasyデータ小屋
%p
  このサイトでは過去に運営されていた定期更新ゲーム『
  Ikki Fantasy
  』
  %span{:style => "font-size:small;"} (公式サイト消滅によりリンク削除)
  を解析して得られる情報を扱っています。
  %br
  結果のリンク先として弊サイト
  = link_to "データ小屋アーカイブス", "https://archives.teiki.org/risu/ikki/1/"
  に保存したものを表示しています。
%br
%p= top_text(@latest_result, @latest_generate, @uploaded_result)

.card.top
  .card-body
    %h2 サイトマップ
    .row
      .col-md-6
        %ul
          %li 個人データ
          %ul
            %li= link_to "キャラクター名・PL名一覧", names_path
            %br
            %li= link_to "現在地一覧", current_areas_path
            %ul
              %li= link_to "エリア進行度別 人数一覧", current_area_totals_path
            %li= link_to "パーティ情報一覧", party_infos_path
            %br
            %li= link_to "ステータス一覧", statuses_path
            %li= link_to "生産Lv一覧", productions_path
            %li= link_to "所持エンブリオ・スキル一覧", skills_path
            %ul
              %li= link_to "エンブリオのみ表示", skills_path + "?base_first=1&show_skill=0"
            %li= link_to "所持アイテム一覧", items_path
            %ul
              %li= link_to "初期装備一覧", init_equips_path
      .col-md-6
        %ul
          %li 戦闘データ
          %ul
            %li= link_to "次回予告NPC戦一覧", next_battle_infos_path
            %li= link_to "次回予告対人戦一覧", next_duel_infos_path
            %li= link_to "NPC戦勝敗一覧", battle_results_path
            %li= link_to "対人戦戦勝敗一覧", duel_results_path
      .col-md-6
        %ul
          %li PKデータ
          %ul
            %li= link_to "PK一覧", pk_data_path
            %ul
              %li= link_to "PK・PKK活動履歴一覧", pk_histories_path
            %li= link_to "次回予告デュエル一覧（次回予告対人戦一覧）", next_duel_infos_path + "?is_duel=on&show_assault=1"
            %li= link_to "デュエル勝敗一覧（対人戦戦勝敗一覧）", duel_results_path + "?is_duel=on&show_assault=1"
      .col-md-6
        %ul
          %li 新出データ
          %ul  
            %li= link_to "新出材料一覧", new_items_path
            %li= link_to "新出装備付加一覧", new_item_fukas_path
            %li= link_to "新出エンブリオ一覧", new_embryos_path
            %li= link_to "新出スキル一覧", new_skills_path
            %li= link_to "新出予告NPC一覧", new_next_enemies_path
            %ul
              %li= link_to "新出予告ボス一覧", new_next_enemies_path + "?base_first=1&is_boss=on"
            %li= link_to "初戦闘NPC一覧", new_battle_enemies_path
            %ul
              %li= link_to "初戦闘ボス一覧", new_battle_enemies_path + "?base_first=1&is_boss=on"
            %li= link_to "ボス初突破一覧", new_defeat_enemies_path
      .col-md-6
        %ul
          %li その他データ
          %ul  
            %li= link_to "エンブリオ・スキル情報一覧", skill_data_path
            %ul
              %li= link_to "エンブリオのみ表示", skill_data_path + "?&base_first=1&show_skill=0&is_form=1"
            %li= link_to "ボス一覧", bosses_path

.card.top
  .card-body
    %h2 更新履歴
    %ul
      %li 2020/9/26
      %ul
        %li サイト公開

app/views/top_page/privacy.html.haml
%h1 プライバシーポリシー
%p 本文書は、当サイト（データ小屋）における個人情報の保護およびその適切な取り扱いについての方針を示したものです。
%br
%h2 当サイトが利用しているアクセス解析ツールに関して
%p (Googleアナリティクス等を使用している場合に記述)
%br
%p 最終更新日：20--年-月-日
%br